resources:
  # Git repo for back-end source
  - name: be_gitRepo
    type: GitRepo
    configuration:
      path: gitta-jfrog/project-examples
      gitProvider: github
 
 
  # Build info for the application
  - name: appl_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: myArtifactory
 
  # Build info for the promoted application
  - name: appl_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: myArtifactory
      
pipelines:
  - name: demo_application
    configuration:
      environmentVariables:
        readOnly:
          JFROG_CLI_BUILD_NAME: backend_build
    steps:
      - name: bld_backend
        type: MvnBuild
        configuration:
          sourceLocation: .
          mvnCommand: clean install -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: be_gitRepo
          integrations:
            - name: myArtifactory
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version
            - mvn --version
 
      - name: build_app
        type: Bash
        configuration:
          environmentVariables:
            dockerImageName: 34.68.55.176:8082/docker-local/app
            dockerImageTag: ${run_number}
          inputResources:
            - name: be_gitRepo
              trigger: false
          inputSteps:
            - name: bld_backend
            - name: publish_frontend
          integrations:
            - name: myArtifactory
        execution:
          onStart:
            - rm -rf $run_dir/workspace/jfrog
            - retry_command jfrog rt config --url $int_myArtifactory_url --user $int_myArtifactory_user --apikey $int_myArtifactory_apikey --interactive=false
            - pushd $res_be_gitRepo_resourcePath
            - add_run_variables buildStepName=${step_name}
            - add_run_variables ${step_name}_buildNumber=${run_number}
            - add_run_variables ${step_name}_buildName=${JFROG_CLI_BUILD_NAME}
            - docker build --pull --no-cache -t $dockerImageName:$dockerImageTag --build-arg REGISTRY=${int_myArtifactory_url} .
            - jfrog rt bce $JFROG_CLI_BUILD_NAME $run_number
            - jfrog rt docker-push 34.68.55.176:8082/docker-local/app:$run_number docker-local
            - add_run_files /tmp/jfrog/. jfrog
 
      - name: publish_app_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: build_app
          outputResources:
            - name: appl_build_info
 
      - name: promote_app_build
        type: PromoteBuild
        configuration:
          targetRepository: demo-pipelines
          integrations:
            - name: myArtifactory
          inputResources:
            - name: appl_build_info
          outputResources:
            - name: appl_promoted_build_info
