pipelines:
  - name: demo_download_repo
    steps:
      - name: download_repo
        type: Bash
        configuration:
          integrations:
            - name: art
        execution:
          onStart:
            - rm -rf $run_dir/workspace/jfrog
            - curl -fL https://getcli.jfrog.io | sh
            - jfrog -v
            - retry_command jfrog rt config --url $int_art_url --user $int_art_user --apikey $int_art_apikey --interactive=false
            - jfrog rt dl generic-repo/ generic-repo/
            - cat generic-repo/readme.txt
