pipelines:
  - name: demo_download_repo
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: "gittalabs.jfrog.io/docker/pipelines-u18node"
            tag: "221120"
            registry: myArtifactory
            sourceRepository: docker
    steps:
      - name: download_repo
        type: Bash
        configuration:
          integrations:
            - name: myArtifactory
        execution:
          onStart:
            - rm -rf $run_dir/workspace/jfrog
            - which jfrog
            - jfrog -v
            - retry_command jfrog rt config --url $int_myArtifactory_url --user $int_myArtifactory_user --apikey $int_myArtifactory_apikey --interactive=false
            - jfrog rt dl generic-repo/ generic-repo/
            - cat generic-repo/readme.txt
