pipelines:
  - name: demo_application
    steps:
      - name: build_app
        type: Bash
          integrations:
            - name: myArtifactory
        execution:
          onStart:
            - rm -rf $run_dir/workspace/jfrog
            - retry_command jfrog rt config --url $int_myArtifactory_url --user $int_myArtifactory_user --apikey $int_myArtifactory_apikey --interactive=false
            - jfrog rt dl local-repo/ my-local-repo/
            - cat my-local-repo/yardeng.pem
